stages:
  - build
  - test
  - deploy

image: mcr.microsoft.com/dotnet/sdk:6.0

build_identity_server_api:
  tags:
    - linux
  stage: build
  script:
    - apt-get update -y && apt-get install sshpass -y
    - cd NetCoreApi/src/Services/IdentityServer/Hawk.Service.IdentityServer.Api
    - ls -a
    - dotnet publish --configuration Release
    - sshpass -e  ssh -o stricthostkeychecking=no deploy@10.10.8.21 %systemroot%/system32/inetsrv/appcmd stop apppool /apppool.name:${CI_COMMIT_REF_NAME}.hawk.acme.dev.internal
    - sshpass -e scp -o stricthostkeychecking=no -v -r bin/Release/net6.0/publish/* deploy@10.10.8.21:D:/Applications/${CI_COMMIT_REF_NAME}.hawk.acme.dev.internal/api/identity
    - sshpass -e  ssh -o stricthostkeychecking=no deploy@10.10.8.21 %systemroot%/system32/inetsrv/appcmd start apppool /apppool.name:${CI_COMMIT_REF_NAME}.hawk.acme.dev.internal

